[package]
name = "tl_cpu"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "CPU tensor backend for TL"
repository = "https://github.com/JunSuzukiJapan/tl"
authors = ["Jun Suzuki"]

[dependencies]
tl_backend = { path = "../tl_backend", version = "0.1.0" }
rand = "0.8"
